### ISSUE TITLE
Status change while on a call.

### ISSUE THREAD

**Issue by robbhartzog** [mattdyer/hipchatskype#1]
I think the data threshold that triggers the status change is too low.  While on a call this morning, it kept jumping to available and back to on a call.  Attached screenshots are during the call.

![screenshot 2017-07-12 09 37 54](https://user-images.githubusercontent.com/645086/28129166-3d04602c-66e7-11e7-8fb7-849862c37746.png)
![screenshot 2017-07-12 09 30 02](https://user-images.githubusercontent.com/645086/28129167-3d06f558-66e7-11e7-90a7-7a862f75041d.png)

**Comment by mattdyer** [comment]
You can pass this threshold value as the third command line argument now.  It defaults to 2000.
